/* SSC CGL Vocab Pro - simple Supabase cloud bridge */
(function () {
  const SUPABASE_URL = 'https://mczrczsnjiruywkzpzny.supabase.co';
  const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jenJjenNuamlydXl3a3pwem55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkyNzc1NjAsImV4cCI6MjEwNDg1MzU2MH0.k_ONkmaI-PdWcSIhIJ6f1FQzOwrCM1lradC3vu9Ujrg';
  let client = null;
  let currentUser = null;
  let loading = false;
  function loadLibrary(){return new Promise((resolve,reject)=>{if(window.supabase&&typeof window.supabase.createClient==='function')return resolve();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=()=>reject(new Error('Supabase library could not be loaded.'));document.head.appendChild(s);});}
  function split(v){if(Array.isArray(v))return v;return String(v||'').split(',').map(x=>x.trim()).filter(Boolean);}
  function fromCloud(r){const asked=Number(r.times_asked||0),correct=Number(r.times_correct||0);return {id:r.word,word:r.word,wordKey:String(r.word||'').trim().toLowerCase(),meaning:r.meaning||'',hindiMeaning:'',partOfSpeech:'',entryNumber:'',categories:split(r.categories),synonyms:r.synonyms||'',antonyms:r.antonyms||'',example:r.example||'',sources:split(r.source),dateAdded:r.created_at||new Date().toISOString(),troublesome:!!r.troublesome,timesAsked:asked,timesCorrect:correct,timesWrong:Number(r.times_wrong||0),accuracy:asked?Math.round(correct/asked*10000)/100:0,lastAsked:r.last_asked||null,lastCorrect:r.last_correct||null,lastWrong:r.last_wrong||null,learningStatus:r.learning_status||'Untested'};}
  function toCloud(w){return {word:String(w.word||'').trim(),user_id:currentUser.id,meaning:String(w.meaning||'').trim(),categories:Array.isArray(w.categories)?w.categories.join(', '):String(w.categories||''),synonyms:String(w.synonyms||'').trim(),antonyms:String(w.antonyms||'').trim(),example:String(w.example||'').trim(),source:Array.isArray(w.sources)?w.sources.join(', '):String(w.source||w.sources||''),troublesome:!!w.troublesome,times_asked:Number(w.timesAsked||0),times_correct:Number(w.timesCorrect||0),times_wrong:Number(w.timesWrong||0),learning_status:String(w.learningStatus||'Untested')};}
  async function cloudWords(){if(!currentUser)return [];const result=await client.from('words').select('*').eq('user_id',currentUser.id).order('word',{ascending:true});if(result.error)throw result.error;return (result.data||[]).map(fromCloud);}
  function installBridge(){window.initDB=async()=>true;window.getAllWordsDB=cloudWords;window.saveWordDB=async w=>{if(!currentUser)throw new Error('Please sign in first.');const result=await client.from('words').upsert(toCloud(w),{onConflict:'word'});if(result.error)throw result.error;return w.id||w.word;};window.bulkSaveWordsDB=async words=>{if(!currentUser)throw new Error('Please sign in first.');const rows=(words||[]).filter(w=>w&&w.word).map(toCloud);if(!rows.length)return;const result=await client.from('words').upsert(rows,{onConflict:'word'});if(result.error)throw result.error;};window.deleteWordDB=async id=>{if(!currentUser)throw new Error('Please sign in first.');const result=await client.from('words').delete().eq('word',String(id||'').trim()).eq('user_id',currentUser.id);if(result.error)throw result.error;};window.wipeDatabase=async()=>{if(!currentUser)throw new Error('Please sign in first.');if(!confirm('DANGER: Are you sure you want to erase ALL your vocabulary entries?'))return;const result=await client.from('words').delete().eq('user_id',currentUser.id);if(result.error)throw result.error;if(typeof window.refreshDataAndUI==='function')await window.refreshDataAndUI();};}
  async function refresh(){if(loading||!currentUser)return;loading=true;try{window.allWordsCache=await cloudWords();if(typeof window.refreshDataAndUI==='function')await window.refreshDataAndUI();console.log('SSC Vocab: cloud vocabulary loaded');}catch(err){console.error('SSC Vocab cloud load failed:',err);if(typeof window.showToast==='function')window.showToast('Cloud load failed: '+(err.message||'unknown error'),'error');}finally{loading=false;}}
  function loginUI(){if(document.getElementById('vocab-auth-overlay'))return;const overlay=document.createElement('div');overlay.id='vocab-auth-overlay';overlay.style.cssText='position:fixed;inset:0;z-index:99999;background:linear-gradient(135deg,#0f172a,#1e3a8a);display:flex;align-items:center;justify-content:center;padding:20px;font-family:Arial,sans-serif;';overlay.innerHTML='<div style="width:100%;max-width:420px;background:white;border-radius:20px;padding:32px;box-shadow:0 25px 60px rgba(0,0,0,.35)"><div style="text-align:center;margin-bottom:24px"><div style="font-size:42px">📚</div><h1 style="margin:0;color:#0f172a;font-size:25px">SSC CGL Vocab Pro</h1><p style="margin:8px 0 0;color:#64748b;font-size:14px">Sign in to access your cloud vocabulary</p></div><input id="vocab-auth-email" type="email" placeholder="Your email" style="width:100%;box-sizing:border-box;padding:12px;border:1px solid #cbd5e1;border-radius:10px;margin-bottom:14px"><input id="vocab-auth-password" type="password" placeholder="Your password" style="width:100%;box-sizing:border-box;padding:12px;border:1px solid #cbd5e1;border-radius:10px;margin-bottom:16px"><button id="vocab-auth-login" style="width:100%;padding:13px;background:#2563eb;color:white;border:0;border-radius:10px;font-weight:700;cursor:pointer">Sign in</button><p id="vocab-auth-error" style="color:#dc2626;font-size:13px;min-height:18px;text-align:center"></p></div>';document.body.appendChild(overlay);const login=async()=>{const email=document.getElementById('vocab-auth-email').value.trim(),password=document.getElementById('vocab-auth-password').value,errBox=document.getElementById('vocab-auth-error');if(!email||!password){errBox.textContent='Enter your email and password.';return;}const btn=document.getElementById('vocab-auth-login');btn.disabled=true;btn.textContent='Signing in...';const result=await client.auth.signInWithPassword({email,password});btn.disabled=false;btn.textContent='Sign in';if(result.error){errBox.textContent=result.error.message;return;}currentUser=result.data.user;overlay.remove();await refresh();};document.getElementById('vocab-auth-login').onclick=login;document.getElementById('vocab-auth-password').onkeydown=e=>{if(e.key==='Enter')login;};document.getElementById('vocab-auth-password').onkeydown=e=>{if(e.key==='Enter')login();};}
  async function setup(){await loadLibrary();client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true}});window.vocabSupabase=client;installBridge();const sessionResult=await client.auth.getSession();if(sessionResult.error)throw sessionResult.error;currentUser=sessionResult.data.session?sessionResult.data.session.user:null;client.auth.onAuthStateChange((_event,session)=>{currentUser=session?session.user:null;if(currentUser){const overlay=document.getElementById('vocab-auth-overlay');if(overlay)overlay.remove();setTimeout(refresh,0);}else loginUI();});if(currentUser)await refresh();else loginUI();}
  window.addEventListener('DOMContentLoaded',()=>setup().catch(err=>{console.error('SSC Vocab setup failed:',err);if(typeof window.showToast==='function')window.showToast('Supabase setup failed: '+(err.message||'unknown error'),'error');}));
})();